### ISSUE TITLE
ENH : loby, location 도메인 crud

### ISSUE THREAD

**Issue by kimhanui** [MeeatNow/MeeatNow#8]
## location: loby = 1: N
- [x] loby crud
- [ ] location crud

## bug
**BUG-1 (해결)**
- 위치: LobyService - insert()   
- 로그: 
**java.lang.StackOverflowError: null**
....(생략)
at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:145) ~[jackson-databind-2.10.2.jar:2.10.2]
      	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107) ~[jackson-databind-2.10.2.jar:2.10.2]
      	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25) ~[jackson-databind-2.10.2.jar:2.10.2]
      	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) ~[jackson-databind-2.10.2.jar:2.10.2]
      	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722) ~[jackson-databind-2.10.2.jar:2.10.2]

- 해결: RestController 어노테이션을 붙인 컨트롤러에서 값을 반환하면 객체를 JSON 타입으로 ObjectMapper 가 변환시켜준다. 여기서 JSON 타입에 대한 무한루프문제가 발생하고 스택오버플로우가 뜬다. 이렇기 때문에 해당 문제를 해결하려면 양방향 매핑을 맺은 필드에 대해서 두 개의 어노테이션을 붙여야 한다.
    ```java
    Loby.java
    @JsonManagedReference        <--  manyToOne인 곳에 이걸 달아주고
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "LOC_ID")
    private Location location;

    Location.java
    @JsonBackReference        <--  oneToMany 인 곳에 이걸 달아주고.
    @OneToMany(mappedBy = "location" , fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private List<Loby> lobies = new ArrayList<>();
    ```

>https://pasudo123.tistory.com/350

**Comment by kimhanui** [comment]
## bug-2 (해결: 다음 코멘트)
- bug: service- isnert() 예외
```java
package com.sejong.eatnow.web.dto;

import com.sejong.eatnow.domain.loby.Loby;
import com.sejong.eatnow.domain.location.Location;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Getter
@NoArgsConstructor
public class LobyRequestDto {

    private String title;
    private String openLink;
    private String hostName;
    private LocalDate meetingDate;
    private LocationDto locationDto; //locationDto로 수정

    public Loby toEntity() {
        Location location = new Location(locationDto.getLatitude(),
                locationDto.getLongitude());
        return Loby.builder()
                .title(title)
                .hostName(hostName)
                .openLink(openLink)
                .location(location)
                .meetingDate(meetingDate)
                .build();
    }
}
```
locationDto로 바꿔줬는데 400에러 뜬다. 
**이유는 location id까지 저장해줘야하는데 안그래서 그런것같다.** <-  도메인이든 dto든 이부분 해결하자

**Comment by kimhanui** [comment]
## 2020-03-10 reference - "ModelMapper"

**dto<-> entity변환 관계매핑엔 ModelMapper**

> 예를 들어, jpa를 사용할때 entity class를 사용하는데 이 entity는 다른 entity들과 관계맵핑이 되어 있기 때문에 이 객체를 client에 바로 response 해주게 되면 관계있는 모든 entity에 대한 쿼리를 날리게 된다.

어쨌든 entity와 dto를 분리하는것은 중요하며 (데이터 가공의 목적? 등 이유는 많다)

entity -> dto 나 dto -> entity로의 변환하는 규칙은 특별히 정해진게 없다. (경험상 노하우가 구조를 탄탄하게 만드는듯)

이런 형태 변환작업은 일반적으로라면 노가다 작업이 필요하다. 뿐만 아니라, 코드 가독성 측면에서 보기에도 안좋다.

이러한 노가다성 작업을 줄여주고 일관적인 코드를 통해 가독성 또한 높여주는 라이브러리들이 있다.

그중 대표적인 라이브러리가 [ModelMapper](http://modelmapper.org/getting-started/)이다.

## 2020-03-11 test
location id가 저장안돼서(값이 안들어가서) 에러가 났으니 id값을 넣어줄건데, 

 - [ ] (case1) java에서 넣어주기엔 다음 id값을 알고있어야하므로 x
 - [x] (case2) **먼저 location엔티티를 저장**해주면서 자연스럽게 id키를 만들게 하자.
            
### 근데 
`locationService`에서 작업하기엔 **_tx이 분리_**(location 저장용, loby저장용)가 안되므로 컨트롤러에서 작업하자
```java
    @Autowired
    private LocationService locationService;       <-- 추가
    private final LobyService service;

    @PostMapping("/insert")
    public ResponseEntity<String> insert(@RequestBody LobyRequestDto dto) {

        ResponseEntity<String> entity = null;
        try {
            locationService.insert(dto.getLocationDto());     <-- 추가
            service.insert(dto);
            entity = new ResponseEntity<>(HttpStatus.OK);
        } catch (Exception e) {
            log.warning(e.getMessage());
            entity = new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);

        }
        return entity;
    }
```

### 결과 : 에러로그
```
com.sejong.eatnow.web.LobyController     : org.hibernate.
TransientPropertyValueException: object references an 
unsaved transient instance - save the transient instance 
before flushing : com.sejong.eatnow.domain.loby.Loby.location
 -> com.sejong.eatnow.domain.location.Location; nested 
exception is java.lang.IllegalStateException: 
org.hibernate.TransientPropertyValueException: 
object references an unsaved transient instance - 
save the transient instance before flushing : com.sejong.
eatnow.domain.loby.Loby.location -> com.sejong.eatnow.domain.
location.Location
```
### 해결방법:
 _`@OneToMany`나 `@ManyToOne`의 연관관계에서 cascadeType.ALL을 설정해주면 된다._

### 다시 시도: 기본으로 돌아가서...    (V 해결)
_컨트롤러 원래대로 되돌리고(locationService만 적용) Location.java의 @OneToMany리스트 필드에만 넣어줫을 땐 안됐는데 **그렇게 안 하고 Loby.java의 @ManyToOne에 넣어주니까 잘 됨**...._
```java
    <Loby.java>
    @ManyToOne(fetch = FetchType.EAGER,  cascade = CascadeType.ALL)   <-- 여기
    @JoinColumn(name = "LOC_ID")
    private Location location;

    <Location.java>
    @OneToMany(mappedBy = "location" , fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private List<Loby> lobies = new ArrayList<>();
```

### ㄹㅇ 왜 됐는지 모르겠다(??)

## 참고 포스트
> https://m.blog.naver.com/PostView.nhn?blogId=writer0713&logNo=221596629064&proxyReferer=https%3A%2F%2Fwww.google.com%2F

> https://yellowh.tistory.com/127

**Comment by kimhanui** [comment]
**[BUG]** LobyService - insert()에서 lobyRequestDto를 저장할때 location 중복저장되는 버그
